function MainPage() {
    return (
        <div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
            <div>app</div>
        </div>
    );
}

export default MainPage;